CREATE TABLE `sur_survey` (
  `BGNO` varchar(3) NOT NULL,
  `SURNO` int(10) NOT NULL,
  `SURTITLE` varchar(200) DEFAULT NULL,
  `SURDATE` varchar(20) DEFAULT NULL,
  `SURSTARTDATE` varchar(20) DEFAULT NULL,
  `SURENDDATE` varchar(20) DEFAULT NULL,
  `SURRESPONSOR` varchar(20) DEFAULT NULL,
  `SURCONTENTS` varchar(5000) DEFAULT NULL,
  `SURSTATE` varchar(20) DEFAULT NULL,
  `USERNO` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `sur_responsor_dtl` (
  `RESDTLNO` varchar(10) NOT NULL,
  `RESNO` varchar(10) NOT NULL,
  `QUENO` varchar(10) DEFAULT NULL,
  `ITEMNO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`RESDTLNO`,`RESNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `sur_response` (
  `RESNO` varchar(10) NOT NULL,
  `RESPONSOR` varchar(20) DEFAULT NULL,
  `RESTIME` varchar(30) DEFAULT NULL,
  `SURNO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`RESNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `sur_question` (
  `QUENO` varchar(10) NOT NULL,
  `QUECONTENTS` varchar(500) DEFAULT NULL,
  `SURNO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`QUENO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `sur_item` (
  `ITEMNO` varchar(10) NOT NULL,
  `ITEMCONTENTS` varchar(200) DEFAULT NULL,
  `QUENO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ITEMNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

