INSERT INTO com_code (CLASSNO, CODECD, CODENM) VALUES
	(2, '1', '임시저장'),
	(2, '2', '결재중'),
    (2, '3', '완료'),
    (2, '4', '반려'),
    (2, '5', '합의거부'),
    (3, 'Y', '결재'),
    (3, 'N', '미결재'),
    (4, '1', '결재'),
    (4, '2', '합의');
       
-- DROP TABLE SGN_SIGN;

CREATE TABLE `SGN_SIGN` (
  `SGNNO` int(11) NOT NULL AUTO_INCREMENT,
  `SGNFLAG` char(1) DEFAULT NULL,
  `SGNDATE` datetime DEFAULT NULL,
  `SGNKIND` char(1) DEFAULT NULL,
  `SDNO` int(11) DEFAULT NULL,
  `USERNO` int(11) DEFAULT NULL,
  `DELETEFLAG` char(1) DEFAULT NULL,
  PRIMARY KEY (`SGNNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SGN_REFERENCE` (
  `REFNO` int(11) NOT NULL AUTO_INCREMENT,
  `REFDATE` datetime DEFAULT NULL,
  `DELETEFLAG` char(1) DEFAULT NULL,
  `SDNO` int(11) DEFAULT NULL,
  `USERNO` int(11) DEFAULT NULL,
  PRIMARY KEY (`REFNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SGN_LINE` (
  `SLNO` int(11) NOT NULL AUTO_INCREMENT,
  `SLTITLE` varchar(255) DEFAULT NULL,
  `SLORDER` int(11) DEFAULT NULL,
  `SLKIND` char(1) DEFAULT NULL,
  `DELETEFLAG` char(1) DEFAULT NULL,
  `USERNO` int(11) DEFAULT NULL,
  PRIMARY KEY (`SLNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SGN_FORM` (
  `FRMNO` int(11) NOT NULL AUTO_INCREMENT,
  `FRMNAME` varchar(1000) DEFAULT NULL,
  `FRMDESC` varchar(100) DEFAULT NULL,
  `DELETEFLAG` char(1) DEFAULT NULL,
  `FRMCONTENTS` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`FRMNO`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

CREATE TABLE `SGN_FILE` (
  `FILENO` int(11) NOT NULL AUTO_INCREMENT,
  `FILENM` varchar(100) DEFAULT NULL,
  `REALFILENM` varchar(30) DEFAULT NULL,
  `FILESIZE` int(11) DEFAULT NULL,
  `SDNO` int(11) DEFAULT NULL,
  PRIMARY KEY (`FILENO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SGN_DOC` (
  `SDNO` int(11) NOT NULL AUTO_INCREMENT,
  `SDTITLE` varchar(255) DEFAULT NULL,
  `SDCONTENTS` varchar(4000) DEFAULT NULL,
  `SDDATE` datetime DEFAULT NULL,
  `SDMODDATE` datetime DEFAULT NULL,
  `DELETEFLAG` char(1) DEFAULT NULL,
  `SDSTATE` char(1) DEFAULT NULL,
  `USERNO` int(11) DEFAULT NULL,
  `FRMNO` int(11) DEFAULT NULL,
  PRIMARY KEY (`SDNO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
