CREATE TABLE `message` (
  `MSGNO` int(11) NOT NULL,
  `SENUSER` varchar(50) NOT NULL,
  `RECUSER` varchar(50) NOT NULL,
  `SENDATE` date DEFAULT NULL,
  `RECDATE` date DEFAULT NULL,
  `FILEYN` tinyint(1) DEFAULT NULL,
  `SENDELYN` tinyint(1) DEFAULT NULL,
  `RECDELYN` tinyint(1) DEFAULT NULL,
  `MSGCONTENTS` text,
  PRIMARY KEY (`MSGNO`)
)

CREATE TABLE `msgfile` (
  `FILENO` int(11) NOT NULL,
  `FILENAME` varchar(100) DEFAULT NULL,
  `REALNAME` varchar(30) DEFAULT NULL,
  `FILESIZE` int(11) DEFAULT NULL,
  `MSGNO` int(11) DEFAULT NULL,
  PRIMARY KEY (`FILENO`),
  KEY `R_4` (`MSGNO`),
  CONSTRAINT `R_4` FOREIGN KEY (`MSGNO`) REFERENCES `message` (`MSGNO`)
)